global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'triglav-server'
    static_configs:
      - targets: ['10.100.0.10:9090']
        labels:
          role: 'server'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
